spring.data.mongodb.database=mocktrade
spring.data.mongodb.uri=mongodb+srv://mockinvest:pbl2@cluster0.fjpzs9e.mongodb.net/mocktrade?retryWrites=true&w=majority
spring.task.scheduling.pool.size=5
logging.level.org.mongodb.driver.cluster=INFO
logging.level.com.mockinvest.backend=DEBUG
server.port=${PORT:8080}
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true

